### ISSUE TITLE
Problem with SNZB-02D

### ISSUE THREAD

**Issue by JohanBendz** [JohanBendz/tech.sonoff#12]
When I add an SNZB-02D Sensor I encounter problems because it does not take into account any settings (decimal, offset, etc.) even if in the console Homey the parameters seem validated. I tested with several SZNB-02D sensors with the same result. Attached you will find screenshots and the result of the Zigbee interview after changing the settings. 

(My note: See local files with screenshoots etc [SNZB-02D map])

**Comment by Sladdgubben** [comment]
Got problem with SNZB-02D in release v0.0.25, app crash
Have installed test release v0.0.26 and it have worked flawless in 24 hours :)
