### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by Barblo1986** [JohanBendz/tech.sonoff#13]
Hello, After the latest update to the Homey app, the SNZB-02 zigbee thermometers no longer work. These give the error: Timeout: Expected Response. 

Restarting the app has had no effect, as has a restart of Homey.  I have created a diagnostic report with the reference: d3ae76bb-9eef-420e-921e-dc9c7b54d372

Hope you can take a look at this, thanks in advance!

**Comment by JohanBendz** [comment]
Hi @Barblo1986, I'm on to this. An update is on it's way.

**Comment by JohanBendz** [comment]
@Barblo1986, any luck with the new test version? https://homey.app/a/tech.sonoff/test/

**Comment by Barblo1986** [comment]
Yes, it is working again with the test link 🙂
Great fast work!
Verstuurd vanaf mijn iPhone

Op 29 jan 2024 om 18:58 heeft Johan Bendz ***@***.***> het volgende geschreven:

﻿

@Barblo1986<https://github.com/Barblo1986>, any luck with the new test version? https://homey.app/a/tech.sonoff/test/

**Comment by JohanBendz** [comment]
Thanks for testing!
