### ISSUE TITLE
Zbmini no longer responding 

### ISSUE THREAD

**Issue by df33f85f86de** [JohanBendz/tech.sonoff#20]
Hi there - ever since my daughter turned the physical light switch, in front of the Zbmini, on and off a few times in a row, the Zbmini is no longer responding to commands. Homey shows that it should be responding (showing on and off to be working) but nothing actually happens. 

Restarting the app in Homey does not work, not does turning off the power (fuse) and turning it back on again. Have not tried a reset on the Zbmini yet.

If anyone has had this problem before, I'm eager to learn your experiences.

Thanks.

**Comment by JohanBendz** [comment]
Hi and sorry for the late answer, hope all is already good againg.

If not...
It sounds like the ZBMini might have gotten stuck after being toggled quickly several times. Here are a couple of things you can try:

Reset the ZBMini: I would recommend performing a factory reset on the ZBMini. This can help if the device has lost sync.

Remove and re-add the device: If resetting doesn't help, try removing the ZBMini from Homey and adding it back again.

If neither of these steps works, feel free to reach out again and we can investigate further.

Good luck!

**Comment by df33f85f86de** [comment]
Much appreciated Johan! I tried the removal from homey before, that didn't have any effect. So will try factory reset! Hopefully without electrocuting myself...
