### ISSUE TITLE
Sonoff SNZB-02

### ISSUE THREAD

**Issue by Engineeronaut** [JohanBendz/tech.sonoff#21]
Unable to update settings for the temp sensors.

One of them keeps dropping out for some reason, every two months or so, so this is the reason for changing settings today. Most likely then the fault is newer than two months. Since the last time I had to add this device again the fult was not present. I see that Sonoff has no update since but homey has I believe, so that might be the issue. 

I get a Network request fail or timeout message when adjusting and trying to save the settings for the temp devices. Nothing is saved either. Same for PC and android.  All other sonoff and other brand devices can be updated in settings. Latest version 0.29 - Homey (2019) 10.0.10. I have restarted Homey and the local router. The sensors are reporting correctly though. 

Another question while I am at it: Is it possible to adjust device settings via Homey script? Report times etcetera?

<img width="281" alt="Skärmbild 2024-06-09 090953" src="https://github.com/JohanBendz/tech.sonoff/assets/116659110/fb5286f7-9538-4630-abd4-a4d27f3c9287">

Regards
/Stefan

**Comment by Boechie** [comment]
@Engineeronaut Your problem could be solved when you press the button on the device very soon after saving the settings (within a few seconds). Improvements to saving the settings are on the way, as @JohanBendz just merged PR #19 to the master branch. I think a new version will be published on a short term.

**Comment by Boechie** [comment]
@Engineeronaut Johan just published the new version as test version. You can already install the new version if you install the TEST version from here: https://homey.app/nl-nl/app/tech.sonoff/SONOFF-Zigbee/test/
