### ISSUE TITLE
SNZB-04 Not recognized

### ISSUE THREAD

**Issue by Granedz** [JohanBendz/tech.sonoff#23]
Trying to add a door/window sensor without success, tried every sonoff app but none will recognize it. Shows up in device list as eWeLink.

Interview info:

  "ids": {
    "modelId": "SNZB-04",
    "manufacturerName": "eWeLink"
  },
  "endpoints": {
    "endpointDescriptors": [
      {
        "endpointId": 1,
        "applicationProfileId": 260,
        "applicationDeviceId": 1026,
        "applicationDeviceVersion": 0,
        "_reserved1": 0,
        "inputClusters": [
          0,
          3,
          1,
          1280,
          32
        ],
        "outputClusters": [
          25
        ]
      }
    ],
    "endpoints": {
      "1": {
        "clusters": {
          "basic": {},
          "identify": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "writable"
                ],
                "id": 0,
                "name": "identifyTime",
                "value": 0
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "powerConfiguration": {
            "attributes": [
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 32,
                "name": "batteryVoltage",
                "value": 30
              },
              {
                "acl": [
                  "readable",
                  "reportable"
                ],
                "id": 33,
                "name": "batteryPercentageRemaining",
                "value": 200
              },
              {
                "acl": [
                  "readable"
                ],
                "id": 65533,
                "name": "clusterRevision",
                "value": 1
              }
            ]
          },
          "iasZone": {},
          "pollControl": {}
        },
        "bindings": {
          "ota": {}
        }
      }
    }
  }

**Comment by JohanBendz** [comment]
Added to next release.
