### ISSUE TITLE
Typo in drivers/ZBMINIL2/device.js on line 30

### ISSUE THREAD

**Issue by Boechie** [JohanBendz/tech.sonoff#28]
On line 30 in file drivers/ZBMINIL2/device.js there is a typo.
See here: https://github.com/JohanBendz/tech.sonoff/blob/2d018ce7ee506c8bbb128aa302d568535d989ba4/drivers/ZBMINIL2/device.js#L30

Current line 30:
`await this.zclNode.endpoints[11].clusters.onOff.writeAttributes({powerOnCtrl: newSettings.powerOnCtrl_state}); // default: On (On, Off, 255 = Recover)`
Must be changed to (the **11** must be changed to **1**):
`await this.zclNode.endpoints[1].clusters.onOff.writeAttributes({powerOnCtrl: newSettings.powerOnCtrl_state}); // default: On (On, Off, 255 = Recover)`

**Comment by JohanBendz** [comment]
Thanks @Boechie, good catch!
Fixed in next update.
