### ISSUE TITLE
v 0.0.25 keep loosing connection with temp-hum sensor SNZB-02D and TH01/SNZB-02 after restart of app

### ISSUE THREAD

**Issue by Boechie** [JohanBendz/tech.sonoff#9]
I installed the latest TEST version of the app (v 0.0.25).

First of all I'm very happy with the fix for the settings of the temp-hum sensors!

However everytime I restart the app on Homey seemingly arbitrary multiple temp-hum sensor loose their connection. In the Homey dev tools I can see that every device reported a few seconds ago. So it doesn't seem to be a zigbee connection problem. Also it seems to help when a device reports a measured value very shortly after the app is restarted (within 1 min or so). Also it seems to help to push the little button of the sensor within that time. Problem is that I can;t make it within 1 minute run around to all my sensors... :-)

Summarizing: I think there is a little problem. Could you look into this? That would be very much appreciated!

**Comment by JohanBendz** [comment]
Hi @Boechie, can you please send a diagnostic report?

**Comment by Boechie** [comment]
I created a diagnostics report: a0f60330-2e78-4ca4-a2db-5727ebb2aad6

**Comment by Boechie** [comment]
Some more information: When I restart the app some (but not all) device drop out (red exclamation mark). See screenshot. 
![image](https://github.com/JohanBendz/tech.sonoff/assets/75488144/af1f5c93-db67-4a10-8dff-3c19cb14ae7f)

It seems as if devices that report a change in measured value, or where the button is pressed, within a minute or so don't drop out immediately. Over last weekend however all device (SNZB-02D and TH01) dropped out. After restarting the app again all TH01 drop out within the minute (I can;t press any button right now), but somehow the SNZB-02D does not show an red exclamation mark, but no fresh value is reported. That was the situation of above diagnostics report.

**Comment by Boechie** [comment]
These are my settings:
![image](https://github.com/JohanBendz/tech.sonoff/assets/75488144/9f389e7c-2ee0-44e7-a186-e645c0db6e35)

I also tried 3600 for the max intervals. Same result. Changing the settings as suggested doesn't revive the devices. Also another restart doesn't make any difference.

**Comment by JohanBendz** [comment]
@Boechie The log does not show any issues with the sensors but your ZBMINI_L devices flood the Zigbee network with reports every other second.

**Comment by Boechie** [comment]
@JohanBendz Oh, that doesn't sound good. Do you have any idea how to solve that?

**Comment by JohanBendz** [comment]
@Boechie, does the new test version solve your problems?
Regarding the flooding it might not be a problem but I will look into it anyway.

**Comment by Boechie** [comment]
@JohanBendz Yes, this seems to work for the connection. No device lost its connection until now (testing for about 10 mins). However, it seems that settings cannot be saved anymore now. The save button stays gray and spinning until timeout after about 30 secs.
![image](https://github.com/JohanBendz/tech.sonoff/assets/75488144/f2d2013b-d317-4539-8865-282be6dbc09e)
![image](https://github.com/JohanBendz/tech.sonoff/assets/75488144/1eb82581-744d-4245-81ac-81dde926d9e2)
In some lucky cases however I was able to get the settings saved. I don't know why/when.

**Comment by JohanBendz** [comment]
@Boechie Yes, I choose to have settings actually work instead of looking like it works 😂 Downside is that when the device is not online (since it's battery operated) the settings will fail.. and you will have to try again until it works. I will put some effort into fixing this problem.

**Comment by Boechie** [comment]
@JohanBendz So, would it help to push the button on the device while it is saving the settings? If so, then that would work for me. ;-)

**Comment by JohanBendz** [comment]
@Boechie Only one way to find out 😉

**Comment by Boechie** [comment]
@JohanBendz Pushing the button while saving seems to work, but... I still get the timeout error during save. After checking the settings again they turn out to be saved.
